<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_datetime</name>
   <tag></tag>
   <elementGuidId>e66d6c66-48f9-4901-95a1-5215426f8315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(normalize-space(.),'${ptn}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(normalize-space(.),'${ptn}')]</value>
   </webElementProperties>
</WebElementEntity>
